# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test this action

on: [push]

jobs:
  test_the_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: encryption test
        uses: ./ # Uses an action in the root directory
        id: pgp
        with:
          text: encryption test
          key: ${{ secrets.PUBLIC_KEY }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: signing test
        uses: ./ # Uses an action in the root directory
        id: pgp2
        with:
          text: signing test
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: keyserver test
        uses: ./ # Uses an action in the root directory
        id: pgp3
        with:
          text: keyserver test
          keysource: keyserver
          keyserver: https://keys.openpgp.org
          key: 708E13848FC62A1F71097F0D73ADA0D5D500BCD6
